# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('campus', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('detail', models.TextField()),
                ('current_num', models.IntegerField(default=0)),
                ('max_num', models.IntegerField()),
                ('reward', models.DecimalField(decimal_places=4, max_digits=5)),
                ('state', models.IntegerField(default=0)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbModel.Order')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hashed_password', models.CharField(max_length=32)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(default='', max_length=11, unique=True)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='ordertouser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbModel.User'),
        ),
    ]
